project:
  type: book

book:
  title: "Don't Think When You Code"
  author: "Joel Karr"
  chapters:
    - index.qmd
    - Preface.md
    - The_Origin.md
    - Deliberate_Practice.md
    - Task_Templates.md
    - Requirements_Alignment.md
    - Ship_Over_Polish.md
    - Instant_Decisions.md
    - Innovation.md
    - The_Core_Doesnt_Change.md

format:
  html:
    number-sections: true
    theme:
      light: flatly
      dark: slate
    css: styles/custom.css
    favicon: images/favicon.png
    title-block: true
    toc: true
    toc-depth: 2
